apiVersion: v1
kind: Service
metadata:
  name: express-container
  namespace: kube-system
spec:
  type: ExternalName
  externalName: express-container.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: express-container
spec:
  selector:
    app: express-container
  ports:
  - port: 3000
