name: Grab version from package.json

on:
    push:
        branches:
            - main
            - develop
    workflow_dispatch:

jobs:
    get-version:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            
            - name: 'Get version from package.json'
              id: get-version
              run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
            
            - name: 'Print out version'
              run: echo '${{ steps.get-version.outputs.VERSION }}'
